### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by Strauch-Yaron** [calebthebrewer/gulp-selectors#10]
Hello,

jQuery-Selectors don't get the new selectors.

Yours,
Yaron

**Comment by calebthebrewer** [comment]
Apologies for the extremely untimely response - I have not had the time to work on this library lately. Implementing all of jQuery's selectors would take more time than I have available so for now I will be closing this issue. If anyone is interested in implementing this themselves it is possible to provide a customer processor as outlined in [the readme](https://github.com/calebthebrewer/gulp-selectors#processors).
