### ISSUE TITLE
using before or after minification?

### ISSUE THREAD

**Issue by nimo23** [calebthebrewer/gulp-selectors#11]
Does it matter if I use this plugin **before** or **after** minification? 

In munchjs (https://www.npmjs.com/package/munchjs)
it is explicitly declared to use its plugin before any minification:

"This library was made solely for the deployment process, and is done at the first steps before minifying the assets"

Should I use gulp-selector before any minifcation? Does it matter?

Does gulp-selectors makes internal use of munch?

**Comment by calebthebrewer** [comment]
Sorry for the late reply, it's been a busy month. You can use this **either** before or after, it doesn't make a difference. One thing to note: I have not yet added support for source-mapping so I only recommend running this for releases and not local development.
