### ISSUE TITLE
Documentation: example output

### ISSUE THREAD

**Issue by mrzmyr** [calebthebrewer/gulp-selectors#14]
It would be great to have a simple example output in the `README.md` to make it more clear how it would work practically. 

Let me know if you'd like a PR.

**Comment by calebthebrewer** [comment]
Yeah I suppose the `README` leaves something to be desired...I'm doing a bit of housecleaning at the moment and threw up #16, if you have a second to review it for helpfulness that would be awesome, (and if you had something else in mind I'm always happy to get  PR).

**Comment by mrzmyr** [comment]
#16 looks great :+1:
