### ISSUE TITLE
Не работает ignores

### ISSUE THREAD

**Issue by Vadizar** [calebthebrewer/gulp-selectors#22]
Не работает игнорирование ID и Class. Пример кода:

var
  gulp = require('gulp'),
  gs = require('gulp-selectors');

var ignores = {
    classes: ['hidden', 'active'],  // ignore these class selectors,
    ids: '*'                        // ignore all IDs
  };

gulp.task('gs', function() {
  gulp.src(['./public/**/*.css', './public/**/*.html'])
    .pipe(gs.run(ignores))
    .pipe(gs.info())
    .pipe(gulp.dest('./dist/'))
});

**Comment by calebthebrewer** [comment]
The first argument for `.run` is the preprocessor objection, if you want to omit this argument you should pass an empty object in first: `gs.run({}, ignores)`.

**Comment by Vadizar** [comment]
How use plugin with AngularJS? I mean data-ng-class.
